<?php
/**
 * Copyright © Experius. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Backend\Block\Template;

/**
 * @var Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script type="text/x-magento-init">
{
    "#media-gallery-image-details": {
        "Magento_Ui/js/core/app": {
            "components": {
                "mediaGalleryImageDetails": {
                    "children": {
                        "fullUrlImageDetails": {
                            "displayArea": "additional_image_details",
                            "component": "uiElement",
                            "template": "Experius_WysiwygDownloads/image/full-url-details"
                        }
                    }
                }
            }
        }
    }
}
</script>
